[package]
name = "tfetch"
version = "0.1.0"
edition = "2021"
authors = ["Thamognya Kodi <contact@thamognya.com>"]
readme = "README.md"
license = "AGPL-3.0-or-later"

[lib]
name = "tfetch"
path = "src/lib.rs"

[[bin]]
name = "tfetch"
path = "src/main.rs"

[dependencies]
